-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
local builtin = require("telescope.builtin")
local mark = require("harpoon.mark")
local ui = require("harpoon.ui")
vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Telescope help tags" })
vim.keymap.set("n", "<leader>fs", function()
  builtin.grep_string({ search = vim.fn.input("grep > ") })
end)
vim.keymap.set("n", "<leader>fg", builtin.git_files, { desc = "Telescope .git" })
-- this is for harpoon
vim.keymap.set("n", "<leader>a", mark.add_file)
vim.keymap.set("n", "<C-e>", ui.toggle_quick_menu)
vim.keymap.set("n", "<A-q>", function()
  ui.nav_file(1)
end)
vim.keymap.set("n", "<A-1>", function()
  ui.nav_file(2)
end)
vim.keymap.set("n", "<A-2>", function()
  ui.nav_file(3)
end)
vim.keymap.set("n", "<A-3>", function()
  ui.nav_file(4)
end)
vim.keymap.set("n", "<A-4>", function()
  ui.nav_file(5)
end)
vim.keymap.set("n", "<A-5>", function()
  ui.nav_file(6)
end)
vim.keymap.set("n", "<C-1>", function()
  ui.nav_file(7)
end)
vim.keymap.set("n", "<C-2>", function()
  ui.nav_file(8)
end)
